server:
  port: 10013
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uxue_qms?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: u-question
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1         #配置逻辑删除以后，只显示该字段为0的数据，MP帮我们处理了业务逻辑
      logic-not-delete-value: 0    #读取的是实体类对应的表字段
      logic-delete-field: delFlag #逻辑删除的字段，把删除请求变为修改，类目不能直接删，而是通过删除标记把0变成1
logging:
  level:
    com:
      offcn: debug
